services:

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=secret
    ports:
      - 8081:8081
    depends_on:
      - redis
        
  STech_API:
    image: api
    build:
      context: .
      dockerfile: STechAPI/Dockerfile
    ports: 
      - 2511:2511
    depends_on: 
      - redis 
  
  STech_Client:
    image: client
    build: 
      context: .
      dockerfile: STech.Client/Dockerfile
    ports: 
      - 5084:5084
    depends_on: 
      - redis
      
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: STech_eCommerce
      POSTGRES_USER: admin
    ports:
      - 5432:5432
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  redis-data:
